language: node_js
node_js:
- lts/*
cache: npm
script:
- npm run deploy
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  target-branch: gh-pages
  github_token: $github_token
  on:
    branch: master